### ISSUE TITLE
4.1-git-exercizes-Aaron-Emery

### ISSUE THREAD

**Issue by a-emery** [TIY-GVL-FEE-2015-August/assignments#150]
## Tasks
- **Getting Started**
  - [x] Follow the assignment instructions to create a new issue.
  - [x] Go through [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) through "Moving Work Around".

- **Git**
  - [x] Fork repository `learn-git-branching` from the class organization page. You will be using the 6 commits in the `master` branch to complete the exercises.

  - Using `git branch`, `git rebase`, etc., make the following changes to your fork of the assignment repository.

    - [x] Create a branch called `exercise-1`. The contents of the branch should be `index.html` with only the boilerplate code and the heading.
    - [x] Create a branch called `exercise-2`. The contents of the branch should be `index.html` with only the boilerplate code and the anchor tag.
    - [x] Create a branch called `exercise-3`. The contents of the branch should be `index.html` with all of the content from `develop`, as well as a `<h2>` with your name below the `<h2>`. The commit containing your name should appear in history immediately after the commit adding the `<h1>`.
    - [x] Create a branch called `exercise-4`. The contents of the branch should be `index.html` with all of the content from `develop`, except the paragraph of text should be removed from the page without being removed from the branch's history.
    - [x] Publish your `exercise-3` to GitHub Pages.

**Comment by a-emery** [comment]
Link: http://a-emery.github.io/learn-git-branching/
Learning Zone: 4.5
Time: 5 hours
Results: I'm not sure. I think I did things right but I have no clue
