### ISSUE TITLE
4.1-Git_Exercises-Laura_Harris

### ISSUE THREAD

**Issue by Laura-Harris** [TIY-GVL-FEE-2015-August/assignments#151]
# Git Exercises

## Tasks
- **Getting Started**
  - [x] Follow the assignment instructions to create a new issue.
  - [x] Go through [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) through "Moving Work Around".

- **Git**
  - [x] Fork repository `learn-git-branching` from the class organization page. You will be using the 6 commits in the `master` branch to complete the exercises.

  - Using `git branch`, `git rebase`, etc., make the following changes to your fork of the assignment repository.

    - [x] Create a branch called `exercise-1`. The contents of the branch should be `index.html` with only the boilerplate code and the heading.
    - [x] Create a branch called `exercise-2`. The contents of the branch should be `index.html` with only the boilerplate code and the anchor tag.
    - [x] Create a branch called `exercise-3`. The contents of the branch should be `index.html` with all of the content from `develop`, as well as a `<h2>` with your name below the `<h2>`. The commit containing your name should appear in history immediately after the commit adding the `<h1>`.
    - [ ] Create a branch called `exercise-4`. The contents of the branch should be `index.html` with all of the content from `develop`, except the paragraph of text should be removed from the page without being removed from the branch's history.
    - [ ] Publish your `exercise-3` to GitHub Pages.

## Additional Resources
- https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
- https://progit.org/
- http://think-like-a-git.net/
- https://www.youtube.com/watch?v=1ffBJ4sVUb4
- http://teamtreehouse.com/library/git-basics

**Comment by Laura-Harris** [comment]
Not completed but wanted to go ahead on close this issue. 

I had some trouble what exactly was expected from each step. Once I got to exercise-3. I made the changes to the index but I need to move the commit location as if it was committed at a different time...?
