### ISSUE TITLE
4.1-Git-Exercises-Joey Gaskin

### ISSUE THREAD

**Issue by joeygaskin** [TIY-GVL-FEE-2015-August/assignments#156]
# Git Exercises

## Tasks
- **Getting Started**
  - [x] Follow the assignment instructions to create a new issue.
  - [x] Go through [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) through "Moving Work Around".

- **Git**
  - [x] Fork repository `learn-git-branching` from the class organization page. You will be using the 6 commits in the `master` branch to complete the exercises.

  - Using `git branch`, `git rebase`, etc., make the following changes to your fork of the assignment repository.

    - [x] Create a branch called `exercise-1`. The contents of the branch should be `index.html` with only the boilerplate code and the heading.
    - [x] Create a branch called `exercise-2`. The contents of the branch should be `index.html` with only the boilerplate code and the anchor tag.
    - [x] Create a branch called `exercise-3`. The contents of the branch should be `index.html` with all of the content from `master`, as well as a `<h2>` with your name below the `<h1>`. The commit containing your name should appear in history immediately after the commit adding the `<h1>`.
    - [x] Create a branch called `exercise-4`. The contents of the branch should be `index.html` with all of the content from `master`, except the paragraph of text should be removed from the page without being removed from the branch's history.
    - [x] Publish your `exercise-3` to GitHub Pages.

## Additional Resources
- https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
- https://progit.org/
- http://think-like-a-git.net/
- https://www.youtube.com/watch?v=1ffBJ4sVUb4
- http://teamtreehouse.com/library/git-basics

**Comment by joeygaskin** [comment]
http://joeygaskin.github.io/learn-git-branching

<b>Learning Zone:</b> 4
<b>Time:</b> 4hrs
<b>Results:</b> I feel like I learned some. I also feel like there's a lot left to learn. I used git checkout, and git branch a lot. I wasn't really sure how to apply git rebase. I assume all of the editing of the index's was to be done in here on GitHub. However, I also did my commits here as well. And I didn't understand the part about the branch history (ie. The commit containing your name should appear in history)
