### ISSUE TITLE
4.1-git-exercises-Pierre-Laferriere

### ISSUE THREAD

**Issue by POLaferriere** [TIY-GVL-FEE-2015-August/assignments#157]
## Tasks
- **Getting Started**
  - [x] Follow the assignment instructions to create a new issue.
  - [x] Go through [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) through "Moving Work Around".

- **Git**
  - [x] Fork repository `learn-git-branching` from the class organization page. You will be using the 6 commits in the `master` branch to complete the exercises.

  - Using `git branch`, `git rebase`, etc., make the following changes to your fork of the assignment repository.

    - [x] Create a branch called `exercise-1`. The contents of the branch should be `index.html` with only the boilerplate code and the heading.
    - [x] Create a branch called `exercise-2`. The contents of the branch should be `index.html` with only the boilerplate code and the anchor tag.
    - [x] Create a branch called `exercise-3`. The contents of the branch should be `index.html` with all of the content from `master`, as well as a `<h2>` with your name below the `<h1>`. The commit containing your name should appear in history immediately after the commit adding the `<h1>`.
    - [x] Create a branch called `exercise-4`. The contents of the branch should be `index.html` with all of the content from `master`, except the paragraph of text should be removed from the page without being removed from the branch's history.
    - [x] Publish your `exercise-3` to GitHub Pages.

**Comment by POLaferriere** [comment]
http://polaferriere.github.io/learn-git-branching

Time: ~3 hours, including reading and exercises
Learning zone: 2-3
Result: I think I'm comfortable with git.  I screwed up a few times but I was able to salvage what I needed to do without any noticeable effects (I think).  I understand the basic principles of git and its uses to manage workflow.  I think that advance uses (such as rebasing commits) will come with practice and necessity.
