### ISSUE TITLE
1.1 Personal Website- Michael Esposito

### ISSUE THREAD

**Issue by Esponage** [TIY-GVL-FEE-2015-August/assignments#17]

**Comment by Esponage** [comment]
Create a portfolio with basic HTML and CSS
Description

Your portfolio will be the initial and primary way that many employers or clients judge your skills as a frontend developer. Eventually it will showcase your projects, but initially we want it to serve as a place to share your contact information.

Objectives

Learning Objectives

After completing this assignment, you should understand...

What HTML and CSS are
How to write semantic, standards-compliant HTML
How to style the presentation of text using CSS
The basics and benefits of git, Github, and Source Control.
Performance Objectives

After completing this assignment, you be able to

Write a basic HTML site from scratch.
Use git to:
check the status and changes to "local" files
add and commit changes to the "local" index
push "local" changes to a Github "remote"
Details

Deliverables

An issue in the class repo titled 1.1 - Personal Website -- YOUR NAME with:
checkboxes as below under Requirements
A repository named 1.1-Personal-Website containing at least:
index.html
main.css
A comment on your Issue with a link to your repository
Requirements

The site should have a landing page with your name, a picture, and email address.
You should have a list of social links to Twitter, GitHub, etc.
Your HTML should pass in the HTML validator at https://html5.validator.nu/
Tasks

 Create a new Issue with these tasks!
 Use the Github app to create a repository 1.1-Personal-Website
 Create your personal website
 Checkpoint: Created and committed index.html
 Checkpoint: Created and committed main.css
 Complete: Pushed index.html and main.css
Additional

**Comment by Esponage** [comment]
# Create a portfolio with basic HTML and CSS

## Description
Your portfolio will be the initial and primary way that many employers or
clients judge your skills as a frontend developer. Eventually it will showcase
your projects, but initially we want it to serve as a place to share your
contact information.

## Objectives

### Learning Objectives

After completing this assignment, you should understand...

* What HTML and CSS are
* How to write semantic, standards-compliant HTML
* How to style the presentation of text using CSS
* The basics and benefits of `git`, Github, and Source Control.

### Performance Objectives

After completing this assignment, you be able to

* Write a basic HTML site from scratch.
* Use `git` to:
    * check the status and changes to "local" files
    * add and commit changes to the "local" index
    * push "local" changes to a Github "remote"

## Details

### Deliverables
* [An issue in the class
  repo](https://github.com/TIY-GVL-FEE-2015-August/assignments) titled `1.1 -
  Personal Website -- YOUR NAME` with:
    * checkboxes as below under _Requirements_
* A repository named `1.1-Personal-Website` containing at least:
  * `index.html`
  * `main.css`
* A comment on your Issue with a link to your repository

### Requirements

* The site should have a landing page with your name, a picture, and email address.
* You should have a list of social links to Twitter, GitHub, etc.
* Your HTML should pass in the HTML validator at https://html5.validator.nu/

### Tasks

* [ ] Create a new Issue with these tasks!
* [ ] Use the Github app to create a  repository `1.1-Personal-Website`
* [ ] Create your personal website
    * [ ] Checkpoint: Created and committed `index.html`
    * [ ] Checkpoint: Created and committed `main.css`
    * [ ] Complete: Pushed `index.html` and `main.css`

## Additional Resources
- Common HTML elements:
  https://github.com/jacobthemyth/flashcards/blob/master/decks/html-elements.md
- Mozilla Developer Network: https://developer.mozilla.org/en-US/
- List of HTML tags: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
- List of HTML attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
- List of CSS properties: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

**Comment by Esponage** [comment]
Learning Zone Score: 2.5
Time Spent: 2 Hours
Results: I finished but feel it could look better.  The issue I had the most was alignment.

https://github.com/Esponage/1.1-personal-website

**Comment by Esponage** [comment]
Here's a link for the blog post-

https://medium.com/@mespo84/first-day-at-the-iron-yard-84cbd14941e1
