### ISSUE TITLE
4.4-github-profile-Aaron-Emery

### ISSUE THREAD

**Issue by a-emery** [TIY-GVL-FEE-2015-August/assignments#195]
## Normal Mode

Build a github profile app that prints out some info from the Github API and your repos. __For the design, you should recreate the Github Repos Tab to the best of your ability__.

> Github tab page: https://github.com/jacobthemyth?tab=repositories

The information from the Github API that you will display includes information from your github user account and repositories.

- Write `$.ajax()` requests to:
    - [x] `https://api.github.com/users/<username>`
    - [x] `https://api.github.com/users/<username>/repos`

- After loading data from the Github API, write at least the following information to the DOM:
    - name
    - blog
    - location
    - email
    - avatar_url
    - html_url
    - and list all of your repositories

### Tasks
- [x] Watch the video [What the heck is the event loop anyway?](https://www.youtube.com/watch?v=8aGhZQkoFbQ)

**Comment by a-emery** [comment]
Link: http://a-emery.github.io/4.4-github-profile/

Time: 15 - 18 hours
Learning Level: 4
Results: I am quite satisfied with my results. Everything is drawing from the GitHub API and lays out pretty well

Repo link: https://github.com/a-emery/4.4-github-profile
