### ISSUE TITLE
1.2 - Blog Layout - Aaron Emery

### ISSUE THREAD

**Issue by a-emery** [TIY-GVL-FEE-2015-August/assignments#36]
### Tasks

* [x] Create banner
* [x] Organize sidebar with logo between banner and text
* [x] Create main content section beside sidebar
* [x] Create follow box in bottom corner

**Comment by a-emery** [comment]
Live link: http://a-emery.github.io/1.2-blog-layout1/

Zone: 3.5
Time: ~4.5 hours
Results: I am quite satisfied with my results. The part that was most difficult was the box in the corner. I think everything turned out pretty well

Repository link: https://github.com/a-emery/1.2-blog-layout1
