### ISSUE TITLE
1.3-timeline-layout- Laura Harris

### ISSUE THREAD

**Issue by Laura-Harris** [TIY-GVL-FEE-2015-August/assignments#45]
# html-intro-4-timeline

## Description

This assignment serves to exercise layout and positioning with CSS.

## Objectives

- exercise control of CSS display types, positioning, animations
- reinforce concepts of layout and `display` types

### Learning Objectives

After completing this assignment, you should be able to create a layout in HTML and CSS from scratch.

### Performance Objectives

After completing this assignment, you should be able to effectively:

- create complex, multi-column layouts, with a variety of different methods; combining multiple approaches to achieve truly creative interface potential

### Deliverables

* A repo containing at least:
    - `index.html`
    - stylesheets
    - `images` folder
        - with any images you used with your design

### Tasks

* **Get Started**
    * [x] Open a new Issue in the class repo and add these checkboxes to your Issue.
    * [x] Create a new repository named `1.3-timeline-layout`.
    * [x] Create and commit an `index.html` file
    * [x] Push your work into Github

* [x]  **Read Learn Layout** if you haven't already

* **Write Some Code**
    * [x] Checkpoint: Initial commit!
    * [x] Checkpoint: Basic page structure (HTML only)!
    * [x] Checkpoint: First line of CSS committed and pushed!
    * [x] Checkpoint: Two column layout achieved.
    * [x] Checkpoint: Colors are exactly right.
    * [ ] Checkpoint: Icons in place.
    * [ ] Checkpoint: Circles and lines finished.
    * [ ] Checkpoint: Hover states and transitions are done. Fancy.
    * [ ] Mission Complete

## Normal Mode

Recreate the following layout in HTML and CSS. Try to get it as close to pixel
perfect as possible. You may slice out the images manually, or use alternative
icons.

Use the `:hover` pseudoclass and the `transition` property to make the different
shades of blue change on hover.

![](./timeline.png)

**Comment by Laura-Harris** [comment]
Files: https://github.com/Laura-Harris/1.3-timeline--Laura-Harris
gh-pages: http://laura-harris.github.io/1.3-timeline--Laura-Harris/

Time: 6-7 hours
Comfort level: 3-4
Results: I am happier with these results than I was on yesterdays project. I understand layout a little more but didn't get other aspects of the page working.
