### ISSUE TITLE
1.3-Timeline-Layouy-Anthony-Bluemmel

### ISSUE THREAD

**Issue by TonyxBlue** [TIY-GVL-FEE-2015-August/assignments#46]
# html-intro-4-timeline

## Description

This assignment serves to exercise layout and positioning with CSS.

## Objectives

- exercise control of CSS display types, positioning, animations
- reinforce concepts of layout and `display` types

### Learning Objectives

After completing this assignment, you should be able to create a layout in HTML and CSS from scratch.

### Performance Objectives

After completing this assignment, you should be able to effectively:

- create complex, multi-column layouts, with a variety of different methods; combining multiple approaches to achieve truly creative interface potential

### Deliverables

* A repo containing at least:
    - `index.html`
    - stylesheets
    - `images` folder
        - with any images you used with your design

### Tasks

* **Get Started**
    * [x] Open a new Issue in the class repo and add these checkboxes to your Issue.
    * [x] Create a new repository named `1.3-timeline-layout`.
    * [x] Create and commit an `index.html` file
    * [x] Push your work into Github

* [x]  **Read Learn Layout** if you haven't already

* **Write Some Code**
    * [x] Checkpoint: Initial commit!
    * [x] Checkpoint: Basic page structure (HTML only)!
    * [x] Checkpoint: First line of CSS committed and pushed!
    * [x] Checkpoint: Two column layout achieved.
    * [x] Checkpoint: Colors are exactly right.
    * [x] Checkpoint: Icons in place.
    * [x] Checkpoint: Circles and lines finished.
    * [ ] Checkpoint: Hover states and transitions are done. Fancy.
    * [ ] Mission Complete

## Normal Mode

Recreate the following layout in HTML and CSS. Try to get it as close to pixel
perfect as possible. You may slice out the images manually, or use alternative
icons.

Use the `:hover` pseudoclass and the `transition` property to make the different
shades of blue change on hover.

![](./timeline.png)

## Hard Mode

Recreate the mobile layout using media queries.

![](./timeline-mobile.png)

## Additional Resources

- http://learnlayout.com/
- http://learn.shayhowe.com/
- List of HTML tags: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
- List of HTML attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
- All the CSS properties! https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

**Comment by TonyxBlue** [comment]
https://github.com/TonyxBlue/1.3-timeline-layout.git

Learning Zone: 4.5ish again. 
Time: All in all, 10 hours.
I didn't finish. I got the icons pretty close to the place they should be but resizing the page causes issues. I couldn't the the vertical lines connecting the the icons. Dates and body line up correctly until you resize. Colors are accurate which might be the lone bright spot. A la, the struggle continues.
