### ISSUE TITLE
1.3-timeline-adam

### ISSUE THREAD

**Issue by adame1194** [TIY-GVL-FEE-2015-August/assignments#47]
### Tasks

* **Get Started**
    * [ ] Open a new Issue in the class repo and add these checkboxes to your Issue.
    * [ ] Create a new repository named `1.3-timeline-layout`.
    * [ ] Create and commit an `index.html` file
    * [ ] Push your work into Github

* [ ]  **Read Learn Layout** if you haven't already

* **Write Some Code**
    * [ ] Checkpoint: Initial commit!
    * [ ] Checkpoint: Basic page structure (HTML only)!
    * [ ] Checkpoint: First line of CSS committed and pushed!
    * [ ] Checkpoint: Two column layout achieved.
    * [ ] Checkpoint: Colors are exactly right.
    * [ ] Checkpoint: Icons in place.
    * [ ] Checkpoint: Circles and lines finished.
    * [ ] Checkpoint: Hover states and transitions are done. Fancy.
    * [ ] Mission Complete
