### ISSUE TITLE
1.3-timeline-layout - Aaron Emery

### ISSUE THREAD

**Issue by a-emery** [TIY-GVL-FEE-2015-August/assignments#49]
### Tasks

* **Get Started**
    * [x] Open a new Issue in the class repo and add these checkboxes to your Issue.
    * [x] Create a new repository named `1.3-timeline-layout`.
    * [x] Create and commit an `index.html` file
    * [x] Push your work into Github

* [x]  **Read Learn Layout** if you haven't already

* **Write Some Code**
    * [x] Checkpoint: Initial commit!
    * [x] Checkpoint: Basic page structure (HTML only)!
    * [x] Checkpoint: First line of CSS committed and pushed!
    * [x] Checkpoint: Two column layout achieved.
    * [x] Checkpoint: Colors are exactly right.
    * [x] Checkpoint: Icons in place.
    * [x] Checkpoint: Circles and lines finished.
    * [x] Checkpoint: Hover states and transitions are done. Fancy.
    * [x] Mission Complete

**Comment by a-emery** [comment]
Viewable at: http://a-emery.github.io/1.3-timeline-layout/

Comfort zone: 4
Time worked: 6 hours
Results: Finished. I'm fairly happy with the outcome. There are some minor problems (the vertical line moves a couple pixels between a full size browser screen and when the mobile kicks in, hover activates on vertical bar), but overall I am quite satisfied.

Repo link: https://github.com/a-emery/1.3-timeline-layout
