### ISSUE TITLE
1.3-timeline-Richard_Freeman

### ISSUE THREAD

**Issue by rfree86** [TIY-GVL-FEE-2015-August/assignments#56]
# html-intro-4-timeline

## Description

This assignment serves to exercise layout and positioning with CSS.

## Objectives

- exercise control of CSS display types, positioning, animations
- reinforce concepts of layout and `display` types

### Learning Objectives

After completing this assignment, you should be able to create a layout in HTML and CSS from scratch.

### Performance Objectives

After completing this assignment, you should be able to effectively:

- create complex, multi-column layouts, with a variety of different methods; combining multiple approaches to achieve truly creative interface potential

### Deliverables

* A repo containing at least:
    - `index.html`
    - stylesheets
    - `images` folder
        - with any images you used with your design

### Tasks

* **Get Started**
    * [x] Open a new Issue in the class repo and add these checkboxes to your Issue.
    * [x] Create a new repository named `1.3-timeline-layout`.
    * [x] Create and commit an `index.html` file
    * [x] Push your work into Github

* [x]  **Read Learn Layout** if you haven't already

* **Write Some Code**
    * [x] Checkpoint: Initial commit!
    * [x] Checkpoint: Basic page structure (HTML only)!
    * [x] Checkpoint: First line of CSS committed and pushed!
    * [x] Checkpoint: Two column layout achieved.
    * [x] Checkpoint: Colors are exactly right.
    * [x] Checkpoint: Icons in place.
    * [x] Checkpoint: Circles and lines finished.
    * [x] Checkpoint: Hover states and transitions are done. Fancy.
    * [x] Mission Complete

**Comment by rfree86** [comment]
https://github.com/rfree86/1.3-timeline-Richard_Freeman.git
time: 7hrs
comfort level: 3.5
results: finished and I am ok with the results.  It got a lot easier once I decided to just give up on the line and move on with the rest.
