### ISSUE TITLE
1.4-Pixel-Perfect-Paul-Nitto

### ISSUE THREAD

**Issue by pnitto** [TIY-GVL-FEE-2015-August/assignments#61]
### Tasks

* **Getting Started**
    * [ ] Follow the assignment instructions to create a new issue.
    * [ ] Follow the assignment instructions to create a new repository.
    * [ ] Create and commit `index.html`
    * [ ] Follow the assignment instructions to create a new pull request.
    * [ ] **Read [this article](http://diveintohtml5.info/semantics.html) about
      semantic HTML.**
* **Make It So**
    * [ ] Checkpoint: Basic HTML structure committed!
    * [ ] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by pnitto** [comment]
Link to Repository:
http://pnitto.github.io/1.4-Pixel-Perfect 

Learning Zone: 4
Timespent: +20 hrs
Results: Its not displaying the same way on gh-pages as it did on my computer screen. I didn't organize my css the best way. I also had some issues with hovering over elements.   All things considered I did learn a lot and got a lot of practice.
