### ISSUE TITLE
1.4-Pixel Perfect- Laura Harris

### ISSUE THREAD

**Issue by Laura-Harris** [TIY-GVL-FEE-2015-August/assignments#63]
# Pixel Perfect Website

## Description
As a developer on the web, you will sometimes be tasked with creating an html
page simply from an image file.  In this assignment, you&#x27;ll be taking an
image and turning it into a functioning website.

### Learning Objectives

Upon completion of this assignment, you should:

* Understand the proper use and function of html tags.
* Understand and able to leverage the many css properties to style content.
* Use CSS to create layout for the HTML page.

### Performance Objectives

After completing this assignment, you should be able to

* Use sectioning html tags
* Effectively utilize some common css layout strategies (float or inline-block)
* Able to leverage and understand the use of `absolute` vs `relative` in context
  of positioning.

### Deliverables

* A repo containing at least:
  * `index.html`
  * 'styles.css'
  * 'images/'

## Normal Mode

* Using the image located in `assets/surf-and-paddle.png`, create a html
  document using html and css to be a pixel perfect match with the image, but be
  a functioning website.
* The menu items, images, and buttons need to also have differing states based
  on a hover, and although not articulated in the provided image, they need to
  be styled.
* Use [these fonts from Google Web
  Fonts](http://www.google.com/fonts#UsePlace:use/Collection:Oswald|Open+Sans)
  in your implementation -- "Open Sans" for most copy, "Oswald" for headings
* Use [the FontAwesome
  icons](http://fortawesome.github.io/Font-Awesome/cheatsheet/) for the
  "Comments", "Read Later", and "Share This" elements
* [placeholder text of your choice](http://meettheipsums.com) for all copy (not headings)
* [placeholder images of your
  choosing](http://www.hanselman.com/blog/TheInternetsBestPlaceholderImageSitesForWebDevelopment.aspx)

![Surf and paddle image](assets/surf-and-paddle.png)

Complete Normal Mode, then make the website fully responsive and adhere to this
[responsive wireframe](assets/surf-and-paddle-responsive.pdf).

### Tasks

* **Getting Started**
    * [x] Follow the assignment instructions to create a new issue.
    * [x] Follow the assignment instructions to create a new repository.
    * [x] Create and commit `index.html`
    * [x] Follow the assignment instructions to create a new pull request.
    * [x] **Read [this article](http://diveintohtml5.info/semantics.html) about
      semantic HTML.**
* **Make It So**
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

## Additional Resources

* Read [Learn Layout](http://learnlayout.com/)

**Comment by Laura-Harris** [comment]
Link: http://laura-harris.github.io/1.4-Pixel-Perfect-Laura-Harris.
Files: https://github.com/Laura-Harris/1.4-Pixel-Perfect-Laura-Harris/tree/gh-pages

Learning zone: 4.5
Time: 20 hours
I didn't finish the overlays since I spent most time on spacing. It definitely is not pixel perfect but I think I still got a better grasp on website layout. It does show up differently depending on the computer screen which is a little disappointing.
