### ISSUE TITLE
1.4-Pixel-Perfect-Layout-Holly Goen

### ISSUE THREAD

**Issue by techgravy** [TIY-GVL-FEE-2015-August/assignments#66]
Well, I screwed up my repository.  I'll deal with the aftermath in the morning.  I hear we're tackling Git this week.  Thank goodness.

# Pixel Perfect Website

## Description
As a developer on the web, you will sometimes be tasked with creating an html
page simply from an image file.  In this assignment, you&#x27;ll be taking an
image and turning it into a functioning website.

### Learning Objectives

Upon completion of this assignment, you should:

* Understand the proper use and function of html tags.
* Understand and able to leverage the many css properties to style content.
* Use CSS to create layout for the HTML page.

### Performance Objectives

After completing this assignment, you should be able to

* Use sectioning html tags
* Effectively utilize some common css layout strategies (float or inline-block)
* Able to leverage and understand the use of `absolute` vs `relative` in context
  of positioning.

### Deliverables

* A repo containing at least:
  * `index.html`
  * 'styles.css'
  * 'images/'

## Normal Mode

* Using the image located in `assets/surf-and-paddle.png`, create a html
  document using html and css to be a pixel perfect match with the image, but be
  a functioning website.
* The menu items, images, and buttons need to also have differing states based
  on a hover, and although not articulated in the provided image, they need to
  be styled.
* Use [these fonts from Google Web
  Fonts](http://www.google.com/fonts#UsePlace:use/Collection:Oswald|Open+Sans)
  in your implementation -- "Open Sans" for most copy, "Oswald" for headings
* Use [the FontAwesome
  icons](http://fortawesome.github.io/Font-Awesome/cheatsheet/) for the
  "Comments", "Read Later", and "Share This" elements
* [placeholder text of your choice](http://meettheipsums.com) for all copy (not headings)
* [placeholder images of your
  choosing](http://www.hanselman.com/blog/TheInternetsBestPlaceholderImageSitesForWebDevelopment.aspx)

![Surf and paddle image](assets/surf-and-paddle.png)

## Hard Mode

Instead of, or in addition to, the Surf and Paddle website:

* Using the image located in `assets/mobber.png`, create a html
  document using html and css to be a pixel perfect match with the image, but be
  a functioning website.
* The menu items and buttons need to also have differing states based on a
  hover, and although not articulated in the provided image, they need to be
  styled.

![Mobber comp](assets/mobber.png)

## Nightmare Mode

Complete Normal Mode, then make the website fully responsive and adhere to this
[responsive wireframe](assets/surf-and-paddle-responsive.pdf).

### Tasks

* **Getting Started**
    * [X] Follow the assignment instructions to create a new issue.
    * [X] Follow the assignment instructions to create a new repository.
    * [X] Create and commit `index.html`
    * [ ] Follow the assignment instructions to create a new pull request.
    * [X] **Read [this article](http://diveintohtml5.info/semantics.html) about
      semantic HTML.**
* **Make It So**
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [x] Checkpoint: Pixel perfect page header committed!
    * [x] Checkpoint: Pixel perfect page footer committed!
    * [x] Checkpoint: Pixel perfect column layout committed!
    * [x] Checkpoint: Pixel perfect layout and typography committed!
    * [x] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

## Additional Resources

* Read [Learn Layout](http://learnlayout.com/)

**Comment by techgravy** [comment]
UPDATE!  Take that internet!  

http://techgravy.github.io/1.4-pixel-perfect-holly-goen/

Learning Level:  4 for some things.  2-3 for others.

Time:  Egads.  At least 24 hours.  Its hard to say because of starting and stopping and completely scrapping the whole thing twice.  Which bothered me a lot less than it would have 6 months ago.  I also spent a lot of time studying the .png and measuring things.  Not that it really helped me do pixel perfect in the end, but it did make me very familiar with the document.  But I'm not sure I would go that route again.  I also did something horrible with Git and I hope to learn how not to do that again.  I'm not happy when there's an unsolved problem, so I'm glad I figured out a work-around.

Results:  In some ways I'm over the moon with happiness that it looks as good as it does.  Well, let's face it, its a crap "site" to begin with so its not like it was going to be an award winner.  I was glad I had time to put my own spin on it.  I'm not a designer by any stretch of the imagination, but why not have some fun every chance you get?  Is it perfect?  Nope.  Did I have fun?  Yep.  Did I learn a ton?  Absolutely.  I'm putting this in the win column.
