### ISSUE TITLE
1.4-Pixel-Perfect-Layout-Anthony-Bluemmel

### ISSUE THREAD

**Issue by TonyxBlue** [TIY-GVL-FEE-2015-August/assignments#68]
### Tasks

* **Getting Started**
    * [x] Follow the assignment instructions to create a new issue.
    * [x] Follow the assignment instructions to create a new repository.
    * [x] Create and commit `index.html`
    * [x] Follow the assignment instructions to create a new pull request.
    * [x] **Read [this article](http://diveintohtml5.info/semantics.html) about
      semantic HTML.**
* **Make It So**
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [x] Mission complete!

## Additional Resources

* Read [Learn Layout](http://learnlayout.com/)

**Comment by TonyxBlue** [comment]
https://github.com/TonyxBlue/1.4-Pixel-Perfect/tree/gh-pages

Learning zone: 4
Time: 24hours
I almost finished it, but I'm disappointed nonetheless. Unfortunately, it's not pixel perfect. I had the header perfect at one time but then things went awry. I had the overlay working on the bottom pictures until they weren't working and I spent so much time racking my brain trying to figure it out but to no avail. At first glance, I think it looks pretty good, but the footer doesn't move uniformly with the page and either does the sidebar. I will say that despite my lack of success I couldn't have even attempted to do what I did for this project 8 days ago so that's a small win. I plan to keep working on it in my free time (if that's a real thing) in order to learn how to do it properly and efficiently and make it the first addition to a portfolio.
