### ISSUE TITLE
1.4 Pixel Perfect 

### ISSUE THREAD

**Issue by krutpatel9** [TIY-GVL-FEE-2015-August/assignments#70]
### Tasks

* **Getting Started**
    * [ ] Follow the assignment instructions to create a new issue.
    * [ ] Follow the assignment instructions to create a new repository.
    * [ ] Create and commit `index.html`
    * [ ] Follow the assignment instructions to create a new pull request.
    * [ ] **Read [this article](http://diveintohtml5.info/semantics.html) about
      semantic HTML.**
* **Make It So**
    * [ ] Checkpoint: Basic HTML structure committed!
    * [ ] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by krutpatel9** [comment]
https://github.com/krutpatel9/1.4-Pixel-Perfect-/tree/gh

comfort zone: 3 
time spent: 6 hours 
End Result :  I got the general layout onto the page however I was unable to get the specifics onto the pages like the hover state and the blue overlay on top of the pictures.
