### ISSUE TITLE
2.2-Sass-RWD-JScottChapman

### ISSUE THREAD

**Issue by jscottchapman** [TIY-GVL-FEE-2015-August/assignments#85]
Estimate of tasks:
-read about bourbon, sass, and neat to try and figure out what the first step is: 1hr
-review the steps for responsive web design:15 minutes
-add the basic structure, layout, and images and content: 15 hours
-all the rest of that stuff: 15 hours

**Comment by jscottchapman** [comment]
# Sk8 Site - Wireframe => HTML

## Description
Without fail, a front-end developer will need to convert a wireframe into a fully functioning website, and responsive at that.

For this assignment, you'll be creating this below wireframe and turning into a site that not only renders well from a normal desktop size, but also transitions and is very usable on smaller viewports.

![Powell Peralta](assets/powell_peralta.jpg)

## Objectives

### Learning Objectives

After completing this assignment, you should…

* Have solid understanding of HTML/CSS/SASS
* Understand principles of RWD and be able to effectively execute a solid flow of content from desktop to mobile.
* Be able to leverage developer tools to test on mobile devices.

### Performance Objectives

After completing this assignment, you be able to effectively use

* From a high fidelity wireframe, you should be able to, with a high degree of accuracy, create an html prototype of said design.
* @media queries
* SASS
* HTML
* manually compile SASS => CSS


## Details

### Deliverables

* A repo containing at least:
  * `index.html`
  * `scss/<sass files>.scss`
  * `css/<css files>.css`


## Normal Mode

* Create a web page from the given Powell Peralta wireframe.
* The finished prototype must be responsive and adjust in a usable way to mobile devices.
* SASS will be written and compiled to CSS

### Tasks

#### Getting Started
  * [ ] Create a new issue with tasks and estimates
  * [ ] Create a new repository
  * [ ] Create and commit `index.html` and `scss/main.scss`
  * [ ] Install Bourbon and Neat
  * [ ] HTML Boilerplate
  * [ ] Add structure using HTML
  * [ ] Add the layout styles for the largest components
  * [ ] Add all images and content

#### Desktop Size
  * [ ] Finish social buttons
  * [ ] Finish nav
  * [ ] Finish header
  * [ ] Finish posts
  * [ ] Finish skateboarders
  * [ ] Finish skateboards
  * [ ] Finish footer

#### Mobile Size
  * [ ] Add mobile styles for social buttons
  * [ ] Add mobile styles for nav
  * [ ] Add mobile styles for header
  * [ ] Add mobile styles for posts
  * [ ] Add mobile styles for skateboarders
  * [ ] Add mobile styles for skateboards
  * [ ] Add mobile styles for footer

## Hard Mode

Do everything just like normal mode, but also add an image slider to the header and the skateboard section and form validation to the contact form at the bottom page.
